### ISSUE TITLE
Geo-restrictions

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/PBSKids.bundle#7]
Why does this not have the same geo-restrictions as the PBS channel, CA and US?

**Comment by sander1** [comment]
Probably because
a) the author of the channel is in the US or CA and didn't know the contents of the channel isn't available outside US and/or CA; or
b) The content used to be available outside the US/CA, but no longer isn't.

**Comment by shopgirl284** [comment]
I think gerk did both this and PBS. Can you play PBS videos? If so, then maybe we just need to remove the restrictions for PBS.

**Comment by shopgirl284** [comment]
This is an old issue and should just be closed
