### ISSUE TITLE
Error when producing full episodes

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/PBSKids.bundle#8]
There is an error when producing full episodes for some shows due to the duration pull from the json. (ex. Arthur)

According to the log:
KeyError: 'iphone' on line 74 in the VideoPage function (duration = item['videos']['iphone']['length'])

Since this is only occurring for some shows, it may just be a blank duration in one or two shows that need a try/except added, but it will require someone looking at the json to know the extent of issues.

**Comment by shopgirl284** [comment]
I tested it and it just needs the duration pull on line 74 put in try/except for it to work again.

**Comment by shopgirl284** [comment]
see Pull Request https://github.com/plexinc-plugins/PBSKids.bundle/pull/9

**Comment by sander1** [comment]
Thanks @shopgirl284!
